# Generated by Django 5.0.6 on 2024-06-13 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('move_type', models.CharField(choices=[('SU', 'Поставка'), ('SH', 'Отгрузка')], help_text='Поставка / Отгрузка', max_length=2, verbose_name='Тип движения')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='manuals.delivery', verbose_name='Способ доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Движения',
                'verbose_name_plural': 'Движение',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='StrProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='manuals.counterparty', verbose_name='Контрагент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='manuals.product', verbose_name='Товар')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='moves.movement', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Строки товаров',
                'verbose_name_plural': 'Строка товара',
                'ordering': ('product',),
            },
        ),
    ]
