# Generated by Django 5.0.6 on 2024-06-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='counterparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='manuals.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='manuals.delivery', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='move_type',
            field=models.CharField(choices=[('SU', 'Поставка'), ('SH', 'Отгрузка')], max_length=2, null=True, verbose_name='Тип движения'),
        ),
    ]
