# Generated by Django 5.0.6 on 2024-06-16 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_alter_movement_counterparty_alter_movement_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strproduct',
            old_name='supply',
            new_name='move',
        ),
        migrations.AlterField(
            model_name='strproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
